version: '3.8'

services:

  tetrika-redis:
    image: bitnami/redis:latest
    container_name: tetrika-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - tetrika-redis-data:/bitnami/redis/data
    networks:
      - tetrika-network

  tetrika-api:
    image: tetrika-api
    container_name: tetrika-api
    ports:
      - "8301:8000"
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: api.dockerfile
    volumes:
      - ./api/app:/app
    networks:
      - tetrika-network

volumes:
  tetrika-redis-data:
    driver: local

networks:
  tetrika-network:
