version: '3.8'

services:

  tetrika-redis:
    image: bitnami/redis:latest
    container_name: tetrika-redis
    volumes:
      - tetrika-redis-data:/bitnami/redis/data

  tetrika-api:
    image: tetrika-api
    container_name: tetrika-api
    ports:
      - "8301:8000"
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: api.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    volumes:
      - ./api/app:/app

volumes:
  tetrika-redis-data:
    driver: local

